### ISSUE TITLE
希望可以增加一个网安备案选项

### ISSUE THREAD

**Issue by dongranliu** [vuepress-reco/vuepress-reco.github.io#12]
[全国互联网安全管理服务平台的链接是 http://www.beian.gov.cn ](http://www.beian.gov.cn)
链接格式是
```html5
![图标](https://img.alicdn.com/tfs/TB1..50QpXXXXX7XpXXXXXXXXXX-40-40.png)[$省公网安备备案号](http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=$备案号)
```

省和备案号需要自定义

类似这样

![图案](https://img.array.fun/img/2019/12/15/456.JPG)

**Comment by recoluan** [comment]
备案是有的，[文档](https://vuepress-theme-reco.recoluan.com/views/1.x/configJs.html#备案信息和项目开始时间)

**Comment by dongranliu** [comment]
现有的是工信部的ICP备案，这个属于公安部的。
谢谢！

**Comment by recoluan** [comment]
好吧，我还没弄过公安部备案，所以不太了解。显示要求是怎么样的呢：
1. 这个公安部的图标必须显示吗？更换图标可以吗（要考虑主题的整体效果）？
2. 还有备案号和图片的样式有专门的要求吗？还是说只要把备案号显示出来就行？

**Comment by dongranliu** [comment]
+ 这个图标是要显示的，开头截图，我截图，是阿里云网站的
+ 要显示公安部图标（图案），x（省份简写）公网安备（文字） 备案号（数字）号（文字），最好不换行
+ 点击上面那串字符串，要能跳转到 `http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=`这个网站，`recordcode=`后边跟上备案号（数字），公安部会有一个专属页面
+ 你可以把省份简写（文字）和备案号（数字），做成可配置项，

**Comment by dongranliu** [comment]
抱歉，突然发现issues提问错仓库了……

**Comment by kachacha** [comment]
请问一下，这个备案号的问题，有解决方案吗？如何在配置那里加上跳转链接？

**Comment by recoluan** [comment]
关于这个问题统一回复一下：

这个问题请先手动修改解决，下个版本会解决。

**Comment by kachacha** [comment]
是生成html后手动解决吗？

**Comment by recoluan** [comment]
对的

**Comment by kachacha** [comment]
好的👌，谢谢！

**Comment by recoluan** [comment]
@kachacha @dongranliu 

请使用最新的测试版 `1.2.0-alpha.13`：

```js
themeConfig = {
  record: 'ICP 备案文案',
  recordLink: 'ICP 备案指向链接',
  cyberSecurityRecord: '公安部备案文案',
  cyberSecurityLink: '公安部备案指向链接'
}
```
