### ISSUE TITLE
把版权所有的图标后面放作者的名字，名字后面放项目开始时间吧

### ISSUE THREAD

**Issue by SquabbyZ** [vuepress-reco/vuepress-reco.github.io#14]
由于本人是用的腾讯云的云服务器，所以需要备案，按照现在的布局来看，腾讯备案客服给的反馈是，版权归属为空，我只能暂时修改你们的源码来调整位置，希望大神解决下这个排版问题，或者增加一个配置项，谢谢。博客地址 http://www.http://www.zhuhaifengz.club/

**Comment by recoluan** [comment]
你的意思是，腾讯那边需要将这两个内容换一下位置吗？如果是的话，我可以调整一下位置，请提供一下客服会话记录，因为腾讯这种要求有点奇葩。

![image](https://user-images.githubusercontent.com/18067907/71556396-2b0b7c00-2a73-11ea-8280-67fd62f90d33.png)

**Comment by SquabbyZ** [comment]
最近比较忙，没有及时回复，抱歉，我微信发给你邮件截图

**Comment by SquabbyZ** [comment]
> 你的意思是，腾讯那边需要将这两个内容换一下位置吗？如果是的话，我可以调整一下位置，请提供一下客服会话记录，因为腾讯这种要求有点奇葩。
> 
> ![image](https://user-images.githubusercontent.com/18067907/71556396-2b0b7c00-2a73-11ea-8280-67fd62f90d33.png)

最近比较忙，没有及时回复，抱歉，我微信发给你邮件截图
