### ISSUE TITLE
1.2.0-alpha.13发现BUG

### ISSUE THREAD

**Issue by SquabbyZ** [vuepress-reco/vuepress-reco.github.io#15]
我在 config.js 的 themeConfig 中配置了 logo 项为自己的图片，type 为默认，PC端显示的正常的 logo 图标，但是移动端博主的头像，默认是作者的头像，只能打包后将 /public/img/home-head 文件名称复制，将自己的 logo 放入到该目录下，改成复制后的名字，希望正式发布的时候能解决，希望能对您起到作用

**Comment by recoluan** [comment]
你好，这里的显示确实存在兼容性问题，新版本中会修复的。
